# Site settings
title: PhDLuffy
SEOTitle: PhDLuffy的博客 | PhDLuffy Blog
header-img: img/post-index-bg-dengziqi.jpg
email: phdluffy@phdluffy.com
description: "我是要成为博士的男人！"
keyword: "PhDLuffy, PhDLuffy Blog, 博客, iOS, Apple, iPhone，Mac"
url: "https://PhDLuffy.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/PhDLuffy/PhDLuffy.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "我是要成为博士的男人！"
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: true
weibo_username:     2313254057
zhihu_username:     PhDLuffy
github_username:    PhDLuffy
#facebook_username:  PhDLuffy
jianshu_username:   085daa6ab5c8
#twitter_username:   PhDLuffy




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10        # posts per page
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0

plugins:
  - jekyll-paginate
  - jekyll-seo-tag




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: phdluffy  #此处前方去掉井号即可恢复Disqus评论系统

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论（true是开启，false是关闭）
  clientID: 226bf4517ab15187f267                            #生成的clientID
  clientSecret: 05c7702acf1ce424dffa1de21e402cf6c5de2dea    #生成的clientSecret
  repo: PhDLuffy.github.io    #仓库名称
  owner: PhDLuffy    #github用户名
  admin: [PhDLuffy]
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 36cad1e424661b0b45a5e74cd0d6c713

# Google Analytics
ga_track_id: 'UA-158657562-1'            # Format: UA-xxxxxx-xx
ga_domain: PhDLuffy.com               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto


include:
  - .well-known


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "PhDLuffy",
        href: "https://phdluffy.com"
    },{
        title: "简书·PhDLuffy",
        href: "http://www.jianshu.com/u/085daa6ab5c8"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
